try
{
    //actual code is written here
}
catch(ExceptionA ex)
{
    // handling exception of type ExceptionA
}
catch(ExceptionB ex)
{
    // handling exception of type ExceptionB
}
finally
{
    // clean up
}